[snowflake]
user = "ALVARO.SANCHEZ@CIVICA-SOFT.COM"
account = "hhfxicv.civicapartner"
authenticator = "externalbrowser"
warehouse = "WH_BASICO"  
database = "ESPECIALIDAD_SQL_BRONCE_DB_ARSR" 
schema = "PUBLIC"
