[snowflake]
user = "ALVARO.SANCHEZ@CIVICA-SOFT.COM"
account = "Alvaro Roque Sanchez Rodriguez"
authenticator = "externalbrowser"
warehouse = "WH_BASICO"  
database = "ESPECIALIDAD_SQL_BRONCE_DB_ARSR" 
schema = "PUBLIC"  
